# Generated by Django 2.0.13 on 2019-05-22 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0003_profesor_cedula'),
        ('alumnos', '0002_auto_20190522_2012'),
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.Alumno')),
            ],
        ),
        migrations.AddField(
            model_name='materia',
            name='profesor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profesores.Profesor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matricula',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.Materia'),
        ),
    ]
