# Generated by Django 2.0.13 on 2019-05-22 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0002_auto_20190522_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='materia',
        ),
        migrations.DeleteModel(
            name='Matricula',
        ),
    ]
