# Generated by Django 2.0.13 on 2019-05-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0003_auto_20190522_2109'),
        ('alumnos', '0002_auto_20190522_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='materia',
            field=models.ManyToManyField(to='materias.Materia'),
        ),
    ]
