# Generated by Django 2.0.13 on 2019-05-22 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profesores',
            new_name='Profesor',
        ),
    ]
