# Generated by Django 2.0.13 on 2019-05-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0002_auto_20190522_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='cedula',
            field=models.CharField(default='123', max_length=12),
            preserve_default=False,
        ),
    ]
